# Generated by Django 4.1.2 on 2022-11-03 12:34

from django.db import migrations, models
import django.db.models.deletion
import pereval.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Added',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=100)),
                ('other_titles', models.CharField(blank=True, max_length=100, null=True)),
                ('connect', models.CharField(blank=True, max_length=200, null=True)),
                ('level_summer', pereval.models.PerevalCategoryField(blank=True, choices=[(1, '1-А'), (2, '1-Б'), (3, '2-А'), (4, '2-Б'), (5, '3-А'), (6, '3-Б')], null=True)),
                ('level_autumn', pereval.models.PerevalCategoryField(blank=True, choices=[(1, '1-А'), (2, '1-Б'), (3, '2-А'), (4, '2-Б'), (5, '3-А'), (6, '3-Б')], null=True)),
                ('level_winter', pereval.models.PerevalCategoryField(blank=True, choices=[(1, '1-А'), (2, '1-Б'), (3, '2-А'), (4, '2-Б'), (5, '3-А'), (6, '3-Б')], null=True)),
                ('level_spring', pereval.models.PerevalCategoryField(blank=True, choices=[(1, '1-А'), (2, '1-Б'), (3, '2-А'), (4, '2-Б'), (5, '3-А'), (6, '3-Б')], null=True)),
                ('latitude', pereval.models.CoordinateField(blank=True, null=True, validators=[pereval.models.validate_coordinates])),
                ('longitude', pereval.models.CoordinateField(blank=True, null=True, validators=[pereval.models.validate_coordinates])),
                ('altitude', pereval.models.HeightField(blank=True, null=True, validators=[pereval.models.validate_height])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fam', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('otc', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to='pereval_photo/')),
                ('title', models.CharField(max_length=100)),
                ('added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.added')),
            ],
            options={
                'ordering': ['added', 'title'],
            },
        ),
    ]
