# Generated by Django 4.1.2 on 2022-11-03 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0002_added_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='added',
            options={'ordering': ['add_time']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email']},
        ),
        migrations.AddField(
            model_name='added',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 12, 52, 52, 394439, tzinfo=datetime.timezone.utc)),
        ),
    ]
