# Generated by Django 4.1.2 on 2022-11-10 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0003_alter_added_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='added',
            name='status',
            field=models.CharField(choices=[('new', 'Загружено пользователем'), ('pending', 'Взято в проверку'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='new', max_length=15),
        ),
        migrations.AlterField(
            model_name='added',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 10, 13, 26, 30, 185801, tzinfo=datetime.timezone.utc)),
        ),
    ]
