# Generated by Django 4.1.2 on 2022-11-12 16:30

from django.db import migrations
import pereval.models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0010_alter_added_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='added',
            name='height',
            field=pereval.models.HeightField(validators=[pereval.models.validate_height]),
        ),
        migrations.AlterField(
            model_name='added',
            name='latitude',
            field=pereval.models.CoordinateField(validators=[pereval.models.validate_coordinates]),
        ),
        migrations.AlterField(
            model_name='added',
            name='longitude',
            field=pereval.models.CoordinateField(validators=[pereval.models.validate_coordinates]),
        ),
    ]
