# Generated by Django 4.1.2 on 2022-10-31 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('established', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DanceGroupDancers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('dance_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_rest_world.dancegroup')),
            ],
            options={
                'ordering': ['dance_group', 'dancer__name'],
            },
        ),
        migrations.CreateModel(
            name='Dancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('born', models.DateField(null=True)),
                ('dance_groups', models.ManyToManyField(through='hello_rest_world.DanceGroupDancers', to='hello_rest_world.dancegroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dancegroupdancers',
            name='dancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_rest_world.dancer'),
        ),
        migrations.AlterUniqueTogether(
            name='dancegroupdancers',
            unique_together={('dancer', 'dance_group')},
        ),
    ]
