# Generated by Django 4.1.2 on 2022-10-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_rest_world', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancer',
            name='born',
            field=models.DateField(blank=True, null=True),
        ),
    ]
